google_analytics: G-X7M75F1G1N
authorbox: disabled
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
highlighter: none
name: Shake's Bunk
title: Hiyaa, It's Shake
description: The Best Way To Get Started Is To Quit Talking And Begin Doing
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ""
disqus: shakes-bunk
mailchimp-list: null
include:
  - _pages
permalink: /:title/
email: abishake.110899@gmail.com
authors:
  - name: abishake
    display_name: Shake
    avatar: assets/images/avatar.png
    gravatar: null
    email: abishake.110899@gmail.com
    web: https://shakeabi.github.io/about
    twitter: null
    description: An aspiring NITT CSE undergrad passionate for building stuff that
      can make an impact at the slightest.
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: "1363087678"
lazyimages: enabled
paginate_path: /blog/page-:num/
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: posts
    values:
      comments: false
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
kramdown:
  syntax_highlighter_opts:
    disable: true
paginate: 6
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
