# Site
name: "Shake's Bunk"
title: "Hiyaa, It's Shake"
description: "A young kid trying to make an impact in this world :)"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
#google_analytics: 'UA-xxxxxxxx-1'
google_analytics: 'G-X7M75F1G1N'
disqus: 'shakes-bunk'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: abishake.110899@gmail.com

# Authors
authors:
  -
    name: abishake
    display_name: Shake    
    avatar: 'assets/images/avatar.png'
    gravatar: 
    email: abishake.110899@gmail.com
    web: https://shakeabi.github.io/about
    twitter: 
    description: "An aspiring NITT CSE undergrad passionate for building stuff that can make an impact at the slightest."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /blog/page-:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
# sass:
#   sass_dir: _sass
#   style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: false
